# Form implementation generated from reading ui file 'cleaning_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_form_cleaning(object):
    def setupUi(self, form_cleaning):
        form_cleaning.setObjectName("form_cleaning")
        form_cleaning.resize(431, 370)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=form_cleaning)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 90, 391, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_clean_temp_folder = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clean_temp_folder.sizePolicy().hasHeightForWidth())
        self.btn_clean_temp_folder.setSizePolicy(sizePolicy)
        self.btn_clean_temp_folder.setObjectName("btn_clean_temp_folder")
        self.gridLayout.addWidget(self.btn_clean_temp_folder, 2, 0, 1, 1)
        self.btn_clean_trash_bin = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clean_trash_bin.sizePolicy().hasHeightForWidth())
        self.btn_clean_trash_bin.setSizePolicy(sizePolicy)
        self.btn_clean_trash_bin.setObjectName("btn_clean_trash_bin")
        self.gridLayout.addWidget(self.btn_clean_trash_bin, 0, 0, 1, 1)
        self.lbl_header = QtWidgets.QLabel(parent=form_cleaning)
        self.lbl_header.setGeometry(QtCore.QRect(50, 20, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header.setFont(font)
        self.lbl_header.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.lbl_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_header.setObjectName("lbl_header")

        self.retranslateUi(form_cleaning)
        QtCore.QMetaObject.connectSlotsByName(form_cleaning)

    def retranslateUi(self, form_cleaning):
        _translate = QtCore.QCoreApplication.translate
        form_cleaning.setWindowTitle(_translate("form_cleaning", "Cleaning"))
        self.btn_clean_temp_folder.setText(_translate("form_cleaning", "Clear Temp Folder"))
        self.btn_clean_trash_bin.setText(_translate("form_cleaning", "Clear Trash Bin"))
        self.lbl_header.setText(_translate("form_cleaning", "Cleaning"))
