# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_main(object):
    def setupUi(self, Form_main):
        Form_main.setObjectName("Form_main")
        Form_main.resize(563, 558)
        Form_main.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        Form_main.setAutoFillBackground(False)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form_main)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 100, 481, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_open_window_startup = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btn_open_window_startup.setObjectName("btn_open_window_startup")
        self.gridLayout.addWidget(self.btn_open_window_startup, 2, 0, 1, 1)
        self.btn_open_window_services = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btn_open_window_services.setObjectName("btn_open_window_services")
        self.gridLayout.addWidget(self.btn_open_window_services, 1, 0, 1, 1)
        self.btn_open_window_taskmanager = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btn_open_window_taskmanager.setObjectName("btn_open_window_taskmanager")
        self.gridLayout.addWidget(self.btn_open_window_taskmanager, 3, 0, 1, 1)
        self.btn_open_window_cleaning = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btn_open_window_cleaning.setObjectName("btn_open_window_cleaning")
        self.gridLayout.addWidget(self.btn_open_window_cleaning, 0, 0, 1, 1)
        self.lbl_header = QtWidgets.QLabel(parent=Form_main)
        self.lbl_header.setGeometry(QtCore.QRect(30, 30, 491, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header.setFont(font)
        self.lbl_header.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.lbl_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_header.setObjectName("lbl_header")

        self.retranslateUi(Form_main)
        QtCore.QMetaObject.connectSlotsByName(Form_main)

    def retranslateUi(self, Form_main):
        _translate = QtCore.QCoreApplication.translate
        Form_main.setWindowTitle(_translate("Form_main", "PC-SpeedBost"))
        self.btn_open_window_startup.setText(_translate("Form_main", "Startup"))
        self.btn_open_window_services.setText(_translate("Form_main", "Services"))
        self.btn_open_window_taskmanager.setText(_translate("Form_main", "Task Management"))
        self.btn_open_window_cleaning.setText(_translate("Form_main", "Cleaning"))
        self.lbl_header.setText(_translate("Form_main", "SPEED MANAGEMENT"))
