# Form implementation generated from reading ui file 'startup_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_form_startup(object):
    def setupUi(self, form_startup):
        form_startup.setObjectName("form_startup")
        form_startup.resize(576, 417)
        self.lbl_header = QtWidgets.QLabel(parent=form_startup)
        self.lbl_header.setGeometry(QtCore.QRect(70, 20, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header.setFont(font)
        self.lbl_header.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.lbl_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_header.setObjectName("lbl_header")
        self.btn_remove_from_startup_apps = QtWidgets.QPushButton(parent=form_startup)
        self.btn_remove_from_startup_apps.setGeometry(QtCore.QRect(460, 90, 101, 61))
        self.btn_remove_from_startup_apps.setObjectName("btn_remove_from_startup_apps")
        self.listview_startupapps = QtWidgets.QListView(parent=form_startup)
        self.listview_startupapps.setGeometry(QtCore.QRect(40, 90, 391, 301))
        self.listview_startupapps.setObjectName("listview_startupapps")

        self.retranslateUi(form_startup)
        QtCore.QMetaObject.connectSlotsByName(form_startup)

    def retranslateUi(self, form_startup):
        _translate = QtCore.QCoreApplication.translate
        form_startup.setWindowTitle(_translate("form_startup", "Startup Apps"))
        self.lbl_header.setText(_translate("form_startup", "Startup Apps"))
        self.btn_remove_from_startup_apps.setText(_translate("form_startup", "Remove"))
